import streamlit as st

title = st.columns([0.25, 0.75])
title[0].image("img/logo.png", width=200)
title[1].title("basil_dock Documentation")

st.header("Overview", divider="gray")
st.write("The basil_dock Streamlit application allows for browser-based and web-based molecular docking and analysis. Once entering the application, users can navigate through different pages using the sidebar on the left. Each page corresponds to a specific step in the molecular docking workflow, from setting general docking parameters to analyzing docking results. The application is designed to be user-friendly and intuitive, providing clear instructions and options for each step of the process.")
st.write("Below is a brief description of each page within the basil_dock application, outlining its purpose and key functionalities.")

st.header("Pages", divider="gray")

st.subheader("General Docking Parameters")
st.write("This page allows users to set various parameters that will be used throughout the docking process, including selecting docking software, selecting docking method (blind or site-specific), and setting variables.")
st.write(":blue[**Select Docking Engine to Use**:] Select docking software to be used (AutoDock Vina or Smina)")
st.write(":blue[**Select Docking Method to Use**:] Select whether to perform blind docking (binding site not predefined) or site-specific docking (binding site predefined by user)")
st.write(":blue[**Select Exhaustiveness Value**:] Set exhaustiveness parameter for docking runs (higher values increase accuracy but also increase computation time)")
st.write(":blue[**Set Number of Docking Modes to Generate**:] Set number of binding poses to generate for each ligand during docking")
st.write(":blue[**Upload Protein Receptor To Use**:] Upload the receptor structure file to use in docking in CIF, ENT, or PDB format")
st.write(":blue[**Upload Ligand/s To Use**:] Upload one or more ligand structure files to use in docking in MOL2, SDF, or PDBQT format")
st.write(":orange[**Output**:] CSV file summarizing imported receptor and ligand information including file names and properties")

st.subheader("Blind Docking")
st.write("This page provides options for performing blind docking studies, where the binding site is not predefined.")
st.write("The blind docking page is automatically loaded after submiting the General Docking Parameters with 'Blind Docking' selected as the docking method.")
st.write(":blue[**Select druggability cutoff to filter pockets for docking**:] Set the druggability score threshold to filter predicted binding pockets for docking")
st.write(":orange[**Output**:] A list of predicted binding pockets that meet the druggability cutoff.")
st.write(":blue[**Update Parameters**:] Updates dataframe with selected pockets for docking.")
st.write(":orange[**Output**:] A dataframe showing the selected pockets for docking along with their properties (volume, surface area, druggability score, center coordinates, dimensions).")
st.write(":blue[**Dock!**:] Initiates the blind docking process using the selected pockets and uploaded ligands.")
st.write(":orange[**Output**:] Docking results including binding poses and scores for each ligand at each selected pocket.")

st.subheader("Site-Specific Docking")
st.write("This page provides options for performing site-specific docking studies, where the binding site is predefined by the user.")
st.write("The site-specific docking page is automatically loaded after submiting the General Docking Parameters with 'Site-Specific Docking' selected as the docking method.")
st.write(":blue[**Review and set parameters for site-specific docking**:] Review and adjust the center coordinates and dimensions of the binding site for docking.")
st.write(":orange[**Output**:] A list of the binding site parameters to be used for docking.")
st.write(":blue[**Dock!**:] Initiates the site-specific docking process using the predefined binding site and uploaded ligands.")
st.write(":orange[**Output**:] Docking results including binding poses and scores for each ligand at the predefined binding site.")

st.subheader("Docking Analysis")
st.write("This page allows users to analyze the results of their docking studies, including viewing binding poses and calculating interaction fingerprints.")
st.write(":blue[**Compare Docking Data**:] View and compare docking scores and other metrics for different ligand conformations.")
st.write(":orange[**Output**:] Visualization of the selected ligand conformations' binding poses within the receptor binding site.")
st.write(":blue[**View interactions between ligand and protein receptor**:] Generate and view interaction fingerprints between the receptor and a ligand conformation.")
st.write(":orange[**Output**:] Interaction fingerprint data and visualization for the selected ligand conformation.")
st.write(":blue[**Calculate Important Binding Features**:] Calculate key binding features between the receptor and a ligand conformation using machine learning regression models.")
st.write(":orange[**Output**:] A dataframe of important binding features and their values for the selected ligand conformation.")
st.write(":blue[**Calculate Important Bioavailability Features**:] Calculate key bioavailability features for all ligands using a machine learning classification model.")
st.write(":orange[**Output**:] A dataframe of important bioavailability features and their values for each ligand.")

st.subheader("Get Ligands via RCSB PDB Advanced Search")
st.write("This page allows users to search for ligands in the RCSB PDB database using advanced search options.")
st.write(":blue[**Search by Chemical Name**:] Enter the chemical name to find relevant ligand structures.")
st.write(":blue[**Search by Chemical Name Synonym**:] Enter the chemical name synonym to find relevant ligand structures.")
st.write(":blue[**Search by Chemical ID**:] Enter the RCSB Chemical ID to find relevant ligand structures.")
st.write(":blue[**Search by Chemical Type**:] Select the chemical type to find relevant ligand structures.")
st.write(":blue[**Search by Chemical Brand Name**:] Enter the DrugBank brand name to find relevant ligand structures.")
st.write(":blue[**Search by Formula Similarity**:] Enter the ligand formula to find relevant ligand structures.")
st.write(":blue[**Search by Structure Similarity**:] Enter the ligand SMILES string to find relevant ligand structures.")
st.write(":orange[**Output**:] A list of ligand identifiers matching the search criteria, along with options to download the corresponding MOL2 file for a selected ligand.")

st.subheader("Generate Ligands from SMILES Strings")
st.write("This page provides options for generating 3D ligand structures from SMILES strings.")
st.write(":blue[**Input Ligand Name and SMILES String**:] Enter the desired ligand name and its corresponding SMILES string.")
st.write(":orange[**Output**:] A 3D structure of the generated ligand in MOL2 format, along with a visualization of the ligand structure.")

st.subheader("Derive Ligands from Existing Ligands")
st.write("This page provides options for deriving new ligands from existing ligand structures.")
st.write(":blue[**Upload Existing Ligand File**:] Upload the existing ligand structure file in MOL2 format.")
st.write(":orange[**Output**:] A list of derived ligands with their corresponding SMILES strings and 3D structures.")

st.write(":blue[**Select Derivative to View**:] Select the type of derivative to view from the generated derivatives.")
st.write(":orange[**Output**:] Visualization of the selected derivative's 3D structure along with its SMILES string.")
st.write(":blue[**Download Derivative Files**:] Option to download the MOL2 and PDBQT files of the derived ligands.")
st.write(":orange[**Output**:] Downloadable MOL2 and PDBQT files for the derived ligands.")

st.subheader("Get Receptors via RCSB PDB Advanced Search")
st.write("This page allows users to search for receptors in the RCSB PDB database using advanced search options.")
st.write(":blue[**Search for Proteins by Enzyme Classification Name**:] Enter the enzyme classification name to find relevant protein structures.")
st.write(":blue[**Search for Proteins by Enzyme Classification Number**:] Enter the enzyme classification number to find relevant protein structures.")
st.write(":blue[**Search for Proteins by Number of Chains**:] Enter the number of chains to find relevant protein structures.")
st.write(":blue[**Search for Proteins by Length of Sequence**:] Enter the length of the sequence to find relevant protein structures.")
st.write(":blue[**Search for Proteins by Molecular Weight**:] Enter the molecular weight to find relevant protein structures.")
st.write(":orange[**Output**:] A list of protein identifiers matching the search criteria, along with options to download the corresponding PDB or CIF file for a selected protein.")
